### ISSUE TITLE
Tracking issue for `set shell := [...]`

### ISSUE THREAD

**Issue by casey** [casey/just#524]
- [x] Finish implementation
- [x] Add tests demonstrating that it can be used to run recipes with `cmd.exe` and powershell
- [x] add documentation in readme
- [x] add to grammar
- [x] Deprecation or upgrade plan for `--shell`
- [x] Make a wishlist issue for a static type system, so I don't have to resort to handling each shell value in the parser
- [x] Release as v0.5.0
- [x] Solicit feedback
- [x] Note in #161 and #326 that this helps.

Close: #361
